name: Release SpaceBoom

on:
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_name: SpaceBoom-linux
          - os: macos-latest
            output_name: SpaceBoom-macos
          - os: windows-latest
            output_name: SpaceBoom-windows.exe

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev xorg-dev libglu1-mesa-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake ninja

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake ninja

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -GNinja ..

      - name: Build
        run: |
          cd build
          ninja

      - name: Prepare release package
        run: |
          mkdir release
          cp build/OpenGL/SpaceBoom${{ matrix.os == 'windows-latest' && '.exe' || '' }} release/${{ matrix.output_name }}
          cp -r OpenGL/res release/res

      - name: Create release archive
        run: |
          cd release
          zip -r ../${{ matrix.output_name }}.zip .

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.output_name }}.zip
          asset_name: ${{ matrix.output_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
